stages:
  preprocess:
    cmd: python P2M/preprocess.py
    deps:
      - P2M/data/raw/Crop_recommendation.csv
    outs:
      - P2M/data/processed/preprocessed_data.csv

  train:
    cmd: python P2M/train.py
    deps:
      - P2M/data/processed/preprocessed_data.csv
    outs:
      - P2M/models/model.pkl

  evaluate:
    cmd: python P2M/evaluate.py
    deps:
      - P2M/models/model.pkl
      - P2M/data/processed/preprocessed_data.csv
    outs:
      - P2M/results/evaluation_metrics.json
