# Generated by Django 5.0.3 on 2024-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P2M', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesures',
            name='rainfall',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
