# Generated by Django 5.0.3 on 2024-03-16 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P2M', '0002_mesures_rainfall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesures',
            new_name='Mesure',
        ),
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
    ]
